// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SecretFolderInitParameters struct {

	// (String) The description of the folder. Defaults to an empty string.
	// The description of the folder. Defaults to an empty string.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The environment slug of the folder to modify/create
	// The environment slug of the folder to modify/create
	EnvironmentSlug *string `json:"environmentSlug,omitempty" tf:"environment_slug,omitempty"`

	// (String) The path where the folder should be created/updated
	// The path where the folder should be created/updated
	FolderPath *string `json:"folderPath,omitempty" tf:"folder_path,omitempty"`

	// (Boolean) Whether to force delete the folder even if it contains resources.
	// Whether to force delete the folder even if it contains resources.
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// (String) The name for the folder
	// The name for the folder
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The Infisical project ID
	// The Infisical project ID (Required for Machine Identity auth, and service tokens with multiple scopes)
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`
}

type SecretFolderObservation struct {

	// (String) The description of the folder. Defaults to an empty string.
	// The description of the folder. Defaults to an empty string.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of the environment
	// The ID of the environment
	EnvironmentID *string `json:"environmentId,omitempty" tf:"environment_id,omitempty"`

	// (String) The environment slug of the folder to modify/create
	// The environment slug of the folder to modify/create
	EnvironmentSlug *string `json:"environmentSlug,omitempty" tf:"environment_slug,omitempty"`

	// (String) The path where the folder should be created/updated
	// The path where the folder should be created/updated
	FolderPath *string `json:"folderPath,omitempty" tf:"folder_path,omitempty"`

	// (Boolean) Whether to force delete the folder even if it contains resources.
	// Whether to force delete the folder even if it contains resources.
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// (String) The ID of the folder
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name for the folder
	// The name for the folder
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The full path of the folder, including its name.
	// The full path of the folder, including its name.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The Infisical project ID
	// The Infisical project ID (Required for Machine Identity auth, and service tokens with multiple scopes)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type SecretFolderParameters struct {

	// (String) The description of the folder. Defaults to an empty string.
	// The description of the folder. Defaults to an empty string.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The environment slug of the folder to modify/create
	// The environment slug of the folder to modify/create
	// +kubebuilder:validation:Optional
	EnvironmentSlug *string `json:"environmentSlug,omitempty" tf:"environment_slug,omitempty"`

	// (String) The path where the folder should be created/updated
	// The path where the folder should be created/updated
	// +kubebuilder:validation:Optional
	FolderPath *string `json:"folderPath,omitempty" tf:"folder_path,omitempty"`

	// (Boolean) Whether to force delete the folder even if it contains resources.
	// Whether to force delete the folder even if it contains resources.
	// +kubebuilder:validation:Optional
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// (String) The name for the folder
	// The name for the folder
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The Infisical project ID
	// The Infisical project ID (Required for Machine Identity auth, and service tokens with multiple scopes)
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`
}

// SecretFolderSpec defines the desired state of SecretFolder
type SecretFolderSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SecretFolderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecretFolderInitParameters `json:"initProvider,omitempty"`
}

// SecretFolderStatus defines the observed state of SecretFolder.
type SecretFolderStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SecretFolderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// SecretFolder is the Schema for the SecretFolders API. Create secret folder & save to Infisical.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type SecretFolder struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environmentSlug) || (has(self.initProvider) && has(self.initProvider.environmentSlug))",message="spec.forProvider.environmentSlug is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.folderPath) || (has(self.initProvider) && has(self.initProvider.folderPath))",message="spec.forProvider.folderPath is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SecretFolderSpec   `json:"spec"`
	Status SecretFolderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecretFolderList contains a list of SecretFolders
type SecretFolderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecretFolder `json:"items"`
}

// Repository type metadata.
var (
	SecretFolder_Kind             = "SecretFolder"
	SecretFolder_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecretFolder_Kind}.String()
	SecretFolder_KindAPIVersion   = SecretFolder_Kind + "." + CRDGroupVersion.String()
	SecretFolder_GroupVersionKind = CRDGroupVersion.WithKind(SecretFolder_Kind)
)

func init() {
	SchemeBuilder.Register(&SecretFolder{}, &SecretFolderList{})
}
