version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - unparam
    - zerologlint
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      enabled-tags:
        - performance
      disabled-checks:
        - appendAssign
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    govet:
      disable:
        - inline
    lll:
      tab-width: 1
    nakedret:
      max-func-lines: 30
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - scopelint
          - unparam
        path: _test(ing)?\.go
      - linters:
          - gocritic
        path: _test\.go
        text: (unnamedResult|exitAfterDefer)
      - linters:
          - gocritic
        text: '(hugeParam|rangeValCopy):'
      - linters:
          - staticcheck
        text: 'SA3000:'
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G104:'
      - linters:
          - gosec
        text: 'G703:'
      - linters:
          - staticcheck
        text: 'SA1019:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/upbound/upjet-provider-template
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
