// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProjectTemplateInitParameters struct {

	// (String) The description of the project template
	// The description of the project template
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The environments for the project template as a JSON string
	// The environments for the project template as a JSON string
	Environments *string `json:"environments,omitempty" tf:"environments,omitempty"`

	// (String) The name of the project template
	// The name of the project template
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The roles for the project template
	// The roles for the project template
	Roles *string `json:"roles,omitempty" tf:"roles,omitempty"`

	// reference/endpoints/project-templates/create#body-type for the available options
	// The type of the project template. Refer to the documentation here https://infisical.com/docs/api-reference/endpoints/project-templates/create#body-type for the available options
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ProjectTemplateObservation struct {

	// (String) The description of the project template
	// The description of the project template
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The environments for the project template as a JSON string
	// The environments for the project template as a JSON string
	Environments *string `json:"environments,omitempty" tf:"environments,omitempty"`

	// (String) The ID of the project template
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the project template
	// The name of the project template
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The roles for the project template
	// The roles for the project template
	Roles *string `json:"roles,omitempty" tf:"roles,omitempty"`

	// reference/endpoints/project-templates/create#body-type for the available options
	// The type of the project template. Refer to the documentation here https://infisical.com/docs/api-reference/endpoints/project-templates/create#body-type for the available options
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ProjectTemplateParameters struct {

	// (String) The description of the project template
	// The description of the project template
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The environments for the project template as a JSON string
	// The environments for the project template as a JSON string
	// +kubebuilder:validation:Optional
	Environments *string `json:"environments,omitempty" tf:"environments,omitempty"`

	// (String) The name of the project template
	// The name of the project template
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The roles for the project template
	// The roles for the project template
	// +kubebuilder:validation:Optional
	Roles *string `json:"roles,omitempty" tf:"roles,omitempty"`

	// reference/endpoints/project-templates/create#body-type for the available options
	// The type of the project template. Refer to the documentation here https://infisical.com/docs/api-reference/endpoints/project-templates/create#body-type for the available options
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ProjectTemplateSpec defines the desired state of ProjectTemplate
type ProjectTemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectTemplateInitParameters `json:"initProvider,omitempty"`
}

// ProjectTemplateStatus defines the observed state of ProjectTemplate.
type ProjectTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectTemplate is the Schema for the ProjectTemplates API. Create project templates & save to Infisical. Only Machine Identity authentication is supported for this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type ProjectTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ProjectTemplateSpec   `json:"spec"`
	Status ProjectTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectTemplateList contains a list of ProjectTemplates
type ProjectTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectTemplate `json:"items"`
}

// Repository type metadata.
var (
	ProjectTemplate_Kind             = "ProjectTemplate"
	ProjectTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectTemplate_Kind}.String()
	ProjectTemplate_KindAPIVersion   = ProjectTemplate_Kind + "." + CRDGroupVersion.String()
	ProjectTemplate_GroupVersionKind = CRDGroupVersion.WithKind(ProjectTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectTemplate{}, &ProjectTemplateList{})
}
