apiVersion: crossplane.infisical.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  host: http://localhost:8088
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: crossplane-system
      key: credentials
