apiVersion: secretrotation.crossplane.infisical.com/v1alpha2
kind: SecretRotationAzureClientSecret
metadata:
  annotations:
    meta.upbound.io/example-id: secretrotation/v1alpha2/secretrotationazureclientsecret
  labels:
    testing.upbound.io/example-name: azure-client-secret
  name: azure-client-secret
spec:
  forProvider:
    connectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    environment: <environment-slug>
    name: azure-client-secret-secret-rotation-example
    parameters:
      clientId: <azure-app-client-id>
      objectId: <azure-app-id>
    projectId: <project-id>
    secretPath: <secret-path>
    secretsMapping:
      clientId: AZURE_CLIENT_ID
      clientSecret: AZURE_CLIENT_SECRET
