// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EnvironmentsInitParameters struct {

	// (String) The name of the project template
	// The name of the environment
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The position of the environment
	// The position of the environment
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// (String) The slug of the environment
	// The slug of the environment
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type EnvironmentsObservation struct {

	// (String) The name of the project template
	// The name of the environment
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The position of the environment
	// The position of the environment
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// (String) The slug of the environment
	// The slug of the environment
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type EnvironmentsParameters struct {

	// (String) The name of the project template
	// The name of the environment
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (Number) The position of the environment
	// The position of the environment
	// +kubebuilder:validation:Optional
	Position *float64 `json:"position" tf:"position,omitempty"`

	// (String) The slug of the environment
	// The slug of the environment
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug" tf:"slug,omitempty"`
}

type GroupsInitParameters struct {

	// (String) The slug of the group
	// The slug of the group
	GroupSlug *string `json:"groupSlug,omitempty" tf:"group_slug,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the group. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type GroupsObservation struct {

	// (String) The slug of the group
	// The slug of the group
	GroupSlug *string `json:"groupSlug,omitempty" tf:"group_slug,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the group. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type GroupsParameters struct {

	// (String) The slug of the group
	// The slug of the group
	// +kubebuilder:validation:Optional
	GroupSlug *string `json:"groupSlug" tf:"group_slug,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the group. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles" tf:"roles,omitempty"`
}

type IdentitiesInitParameters struct {

	// (String) The ID of the identity
	// The ID of the identity
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the identity. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type IdentitiesObservation struct {

	// (String) The ID of the identity
	// The ID of the identity
	IdentityID *string `json:"identityId,omitempty" tf:"identity_id,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the identity. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`
}

type IdentitiesParameters struct {

	// (String) The ID of the identity
	// The ID of the identity
	// +kubebuilder:validation:Optional
	IdentityID *string `json:"identityId" tf:"identity_id,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the identity. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles" tf:"roles,omitempty"`
}

type ProjectTemplateInitParameters struct {

	// (String) The description of the project template
	// The description of the project template
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Attributes List) The environments for the project template (see below for nested schema)
	Environments []EnvironmentsInitParameters `json:"environments,omitempty" tf:"environments,omitempty"`

	// (Attributes Set) The groups assigned to projects created from this template (see below for nested schema)
	Groups []GroupsInitParameters `json:"groups,omitempty" tf:"groups,omitempty"`

	// (Attributes Set) The identities assigned to projects created from this template (see below for nested schema)
	Identities []IdentitiesInitParameters `json:"identities,omitempty" tf:"identities,omitempty"`

	// (String) The name of the project template
	// The name of the project template
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	Roles []ProjectTemplateRolesInitParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// reference/endpoints/project-templates/create#body-type for the available options
	// The type of the project template. Refer to the documentation here https://infisical.com/docs/api-reference/endpoints/project-templates/create#body-type for the available options
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Attributes Set) The users assigned to projects created from this template (see below for nested schema)
	Users []UsersInitParameters `json:"users,omitempty" tf:"users,omitempty"`
}

type ProjectTemplateObservation struct {

	// (String) The description of the project template
	// The description of the project template
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Attributes List) The environments for the project template (see below for nested schema)
	Environments []EnvironmentsObservation `json:"environments,omitempty" tf:"environments,omitempty"`

	// (Attributes Set) The groups assigned to projects created from this template (see below for nested schema)
	Groups []GroupsObservation `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) The ID of the project template
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes Set) The identities assigned to projects created from this template (see below for nested schema)
	Identities []IdentitiesObservation `json:"identities,omitempty" tf:"identities,omitempty"`

	// (String) The name of the project template
	// The name of the project template
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	Roles []ProjectTemplateRolesObservation `json:"roles,omitempty" tf:"roles,omitempty"`

	// reference/endpoints/project-templates/create#body-type for the available options
	// The type of the project template. Refer to the documentation here https://infisical.com/docs/api-reference/endpoints/project-templates/create#body-type for the available options
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Attributes Set) The users assigned to projects created from this template (see below for nested schema)
	Users []UsersObservation `json:"users,omitempty" tf:"users,omitempty"`
}

type ProjectTemplateParameters struct {

	// (String) The description of the project template
	// The description of the project template
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Attributes List) The environments for the project template (see below for nested schema)
	// +kubebuilder:validation:Optional
	Environments []EnvironmentsParameters `json:"environments,omitempty" tf:"environments,omitempty"`

	// (Attributes Set) The groups assigned to projects created from this template (see below for nested schema)
	// +kubebuilder:validation:Optional
	Groups []GroupsParameters `json:"groups,omitempty" tf:"groups,omitempty"`

	// (Attributes Set) The identities assigned to projects created from this template (see below for nested schema)
	// +kubebuilder:validation:Optional
	Identities []IdentitiesParameters `json:"identities,omitempty" tf:"identities,omitempty"`

	// (String) The name of the project template
	// The name of the project template
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) The roles for the project template (see below for nested schema)
	// +kubebuilder:validation:Optional
	Roles []ProjectTemplateRolesParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// reference/endpoints/project-templates/create#body-type for the available options
	// The type of the project template. Refer to the documentation here https://infisical.com/docs/api-reference/endpoints/project-templates/create#body-type for the available options
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Attributes Set) The users assigned to projects created from this template (see below for nested schema)
	// +kubebuilder:validation:Optional
	Users []UsersParameters `json:"users,omitempty" tf:"users,omitempty"`
}

type ProjectTemplateRolesInitParameters struct {

	// (String) The name of the project template
	// The name of the role
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// reference/endpoints/project-templates/create#body-roles-permissions for its usage. (see below for nested schema)
	Permissions []RolesPermissionsInitParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) The slug of the environment
	// The slug of the role
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type ProjectTemplateRolesObservation struct {

	// (String) The name of the project template
	// The name of the role
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// reference/endpoints/project-templates/create#body-roles-permissions for its usage. (see below for nested schema)
	Permissions []RolesPermissionsObservation `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) The slug of the environment
	// The slug of the role
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type ProjectTemplateRolesParameters struct {

	// (String) The name of the project template
	// The name of the role
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// reference/endpoints/project-templates/create#body-roles-permissions for its usage. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Permissions []RolesPermissionsParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) The slug of the environment
	// The slug of the role
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug" tf:"slug,omitempty"`
}

type RolesPermissionsInitParameters struct {

	// (Set of String) Describe what actions an entity can take.
	// Describe what actions an entity can take.
	// +listType=set
	Action []*string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	// When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	Conditions *string `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Boolean) Whether rule forbids. Set this to true if permission forbids.
	// Whether rule forbids. Set this to true if permission forbids.
	Inverted *bool `json:"inverted,omitempty" tf:"inverted,omitempty"`

	// (String) Describe the entity the permission pertains to.
	// Describe the entity the permission pertains to.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type RolesPermissionsObservation struct {

	// (Set of String) Describe what actions an entity can take.
	// Describe what actions an entity can take.
	// +listType=set
	Action []*string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	// When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	Conditions *string `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Boolean) Whether rule forbids. Set this to true if permission forbids.
	// Whether rule forbids. Set this to true if permission forbids.
	Inverted *bool `json:"inverted,omitempty" tf:"inverted,omitempty"`

	// (String) Describe the entity the permission pertains to.
	// Describe the entity the permission pertains to.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type RolesPermissionsParameters struct {

	// (Set of String) Describe what actions an entity can take.
	// Describe what actions an entity can take.
	// +kubebuilder:validation:Optional
	// +listType=set
	Action []*string `json:"action" tf:"action,omitempty"`

	// (String) When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	// When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	// +kubebuilder:validation:Optional
	Conditions *string `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Boolean) Whether rule forbids. Set this to true if permission forbids.
	// Whether rule forbids. Set this to true if permission forbids.
	// +kubebuilder:validation:Optional
	Inverted *bool `json:"inverted,omitempty" tf:"inverted,omitempty"`

	// (String) Describe the entity the permission pertains to.
	// Describe the entity the permission pertains to.
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type UsersInitParameters struct {

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the user. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) The username of the user.
	// The username of the user.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UsersObservation struct {

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the user. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) The username of the user.
	// The username of the user.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UsersParameters struct {

	// (Attributes List) The roles for the project template (see below for nested schema)
	// The role slugs to assign to the user. Must reference roles defined in this template or predefined role slugs (admin, member, viewer, no-access).
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles" tf:"roles,omitempty"`

	// (String) The username of the user.
	// The username of the user.
	// +kubebuilder:validation:Optional
	Username *string `json:"username" tf:"username,omitempty"`
}

// ProjectTemplateSpec defines the desired state of ProjectTemplate
type ProjectTemplateSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ProjectTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectTemplateInitParameters `json:"initProvider,omitempty"`
}

// ProjectTemplateStatus defines the observed state of ProjectTemplate.
type ProjectTemplateStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ProjectTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectTemplate is the Schema for the ProjectTemplates API. Create project templates & save to Infisical. Only Machine Identity authentication is supported for this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type ProjectTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ProjectTemplateSpec   `json:"spec"`
	Status ProjectTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectTemplateList contains a list of ProjectTemplates
type ProjectTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectTemplate `json:"items"`
}

// Repository type metadata.
var (
	ProjectTemplate_Kind             = "ProjectTemplate"
	ProjectTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectTemplate_Kind}.String()
	ProjectTemplate_KindAPIVersion   = ProjectTemplate_Kind + "." + CRDGroupVersion.String()
	ProjectTemplate_GroupVersionKind = CRDGroupVersion.WithKind(ProjectTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectTemplate{}, &ProjectTemplateList{})
}
