// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ProjectGroupInitParameters struct {

	// (String) The id of the group.
	// The id of the group.
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/group/v1alpha2.Group
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a Group in group to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v2.Reference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a Group in group to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v2.Selector `json:"groupIdSelector,omitempty" tf:"-"`

	// (String) The name of the group.
	// The name of the group.
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// (String) The id of the project.
	// The id of the project.
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha2.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes Set) The roles assigned to the project group (see below for nested schema)
	Roles []RolesInitParameters `json:"roles,omitempty" tf:"roles,omitempty"`
}

type ProjectGroupObservation struct {

	// (String) The id of the group.
	// The id of the group.
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// (String) The name of the group.
	// The name of the group.
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The membership Id of the project group
	// The membership Id of the project group
	MembershipID *string `json:"membershipId,omitempty" tf:"membership_id,omitempty"`

	// (String) The id of the project.
	// The id of the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes Set) The roles assigned to the project group (see below for nested schema)
	Roles []RolesObservation `json:"roles,omitempty" tf:"roles,omitempty"`
}

type ProjectGroupParameters struct {

	// (String) The id of the group.
	// The id of the group.
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/group/v1alpha2.Group
	// +kubebuilder:validation:Optional
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a Group in group to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v2.Reference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a Group in group to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v2.Selector `json:"groupIdSelector,omitempty" tf:"-"`

	// (String) The name of the group.
	// The name of the group.
	// +kubebuilder:validation:Optional
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// (String) The id of the project.
	// The id of the project.
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha2.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes Set) The roles assigned to the project group (see below for nested schema)
	// +kubebuilder:validation:Optional
	Roles []RolesParameters `json:"roles,omitempty" tf:"roles,omitempty"`
}

type RolesInitParameters struct {

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	RoleSlug *string `json:"roleSlug,omitempty" tf:"role_slug,omitempty"`

	// MM-DDTHH:MM:SSZ e.g. 2024-09-19T12:43:13Z
	// ISO time for which temporary access should begin. This is in the format YYYY-MM-DDTHH:MM:SSZ e.g. 2024-09-19T12:43:13Z
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

type RolesObservation struct {

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	RoleSlug *string `json:"roleSlug,omitempty" tf:"role_slug,omitempty"`

	// MM-DDTHH:MM:SSZ e.g. 2024-09-19T12:43:13Z
	// ISO time for which temporary access should begin. This is in the format YYYY-MM-DDTHH:MM:SSZ e.g. 2024-09-19T12:43:13Z
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

type RolesParameters struct {

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// +kubebuilder:validation:Optional
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	// +kubebuilder:validation:Optional
	RoleSlug *string `json:"roleSlug" tf:"role_slug,omitempty"`

	// MM-DDTHH:MM:SSZ e.g. 2024-09-19T12:43:13Z
	// ISO time for which temporary access should begin. This is in the format YYYY-MM-DDTHH:MM:SSZ e.g. 2024-09-19T12:43:13Z
	// +kubebuilder:validation:Optional
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// +kubebuilder:validation:Optional
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

// ProjectGroupSpec defines the desired state of ProjectGroup
type ProjectGroupSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ProjectGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectGroupInitParameters `json:"initProvider,omitempty"`
}

// ProjectGroupStatus defines the observed state of ProjectGroup.
type ProjectGroupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ProjectGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectGroup is the Schema for the ProjectGroups API. Add an existing group to a project and assign it project roles. Exactly one of group_id or group_name must be set. This resource does not create groups; to create a group, use the infisical_group resource. Destroying this resource removes the group from the project; the group itself is left untouched. Only Machine Identity authentication is supported for this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type ProjectGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	Spec   ProjectGroupSpec   `json:"spec"`
	Status ProjectGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectGroupList contains a list of ProjectGroups
type ProjectGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectGroup `json:"items"`
}

// Repository type metadata.
var (
	ProjectGroup_Kind             = "ProjectGroup"
	ProjectGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectGroup_Kind}.String()
	ProjectGroup_KindAPIVersion   = ProjectGroup_Kind + "." + CRDGroupVersion.String()
	ProjectGroup_GroupVersionKind = CRDGroupVersion.WithKind(ProjectGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectGroup{}, &ProjectGroupList{})
}
