// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ProjectUserInitParameters struct {

	// (String) The id of the project
	// The id of the project
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha2.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes List) The roles assigned to the project user (see below for nested schema)
	Roles []ProjectUserRolesInitParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) The usename of the user. By default its the email
	// The usename of the user. By default its the email
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ProjectUserObservation struct {

	// (String) The ID of the project user role.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The membershipId of the project user
	// The membershipId of the project user
	MembershipID *string `json:"membershipId,omitempty" tf:"membership_id,omitempty"`

	// (String) The id of the project
	// The id of the project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes List) The roles assigned to the project user (see below for nested schema)
	Roles []ProjectUserRolesObservation `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Attributes) The user details of the project user (see below for nested schema)
	User *UserObservation `json:"user,omitempty" tf:"user,omitempty"`

	// (String) The usename of the user. By default its the email
	// The usename of the user. By default its the email
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ProjectUserParameters struct {

	// (String) The id of the project
	// The id of the project
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha2.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes List) The roles assigned to the project user (see below for nested schema)
	// +kubebuilder:validation:Optional
	Roles []ProjectUserRolesParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) The usename of the user. By default its the email
	// The usename of the user. By default its the email
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ProjectUserRolesInitParameters struct {

	// (String) The id of the custom role slug
	// The id of the custom role slug
	CustomRoleID *string `json:"customRoleId,omitempty" tf:"custom_role_id,omitempty"`

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	RoleSlug *string `json:"roleSlug,omitempty" tf:"role_slug,omitempty"`

	// (String) ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	// ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	TemporaryAccessEndTime *string `json:"temporaryAccessEndTime,omitempty" tf:"temporary_access_end_time,omitempty"`

	// (String) ISO time for which temporary access should begin. The current time is used by default.
	// ISO time for which temporary access should begin. The current time is used by default.
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) Type of temporary access given. Types: relative. Default: relative
	// Type of temporary access given. Types: relative. Default: relative
	TemporaryMode *string `json:"temporaryMode,omitempty" tf:"temporary_mode,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

type ProjectUserRolesObservation struct {

	// (String) The id of the custom role slug
	// The id of the custom role slug
	CustomRoleID *string `json:"customRoleId,omitempty" tf:"custom_role_id,omitempty"`

	// (String) The ID of the project user role.
	// The ID of the project user role.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	RoleSlug *string `json:"roleSlug,omitempty" tf:"role_slug,omitempty"`

	// (String) ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	// ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	TemporaryAccessEndTime *string `json:"temporaryAccessEndTime,omitempty" tf:"temporary_access_end_time,omitempty"`

	// (String) ISO time for which temporary access should begin. The current time is used by default.
	// ISO time for which temporary access should begin. The current time is used by default.
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) Type of temporary access given. Types: relative. Default: relative
	// Type of temporary access given. Types: relative. Default: relative
	TemporaryMode *string `json:"temporaryMode,omitempty" tf:"temporary_mode,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

type ProjectUserRolesParameters struct {

	// (String) The id of the custom role slug
	// The id of the custom role slug
	// +kubebuilder:validation:Optional
	CustomRoleID *string `json:"customRoleId,omitempty" tf:"custom_role_id,omitempty"`

	// (Boolean) Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// Flag to indicate the assigned role is temporary or not. When is_temporary is true fields temporary_mode, temporary_range and temporary_access_start_time is required.
	// +kubebuilder:validation:Optional
	IsTemporary *bool `json:"isTemporary,omitempty" tf:"is_temporary,omitempty"`

	// (String) The slug of the role
	// The slug of the role
	// +kubebuilder:validation:Optional
	RoleSlug *string `json:"roleSlug" tf:"role_slug,omitempty"`

	// (String) ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	// ISO time for which temporary access will end. Computed based on temporary_range and temporary_access_start_time
	// +kubebuilder:validation:Optional
	TemporaryAccessEndTime *string `json:"temporaryAccessEndTime,omitempty" tf:"temporary_access_end_time,omitempty"`

	// (String) ISO time for which temporary access should begin. The current time is used by default.
	// ISO time for which temporary access should begin. The current time is used by default.
	// +kubebuilder:validation:Optional
	TemporaryAccessStartTime *string `json:"temporaryAccessStartTime,omitempty" tf:"temporary_access_start_time,omitempty"`

	// (String) Type of temporary access given. Types: relative. Default: relative
	// Type of temporary access given. Types: relative. Default: relative
	// +kubebuilder:validation:Optional
	TemporaryMode *string `json:"temporaryMode,omitempty" tf:"temporary_mode,omitempty"`

	// (String) TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// TTL for the temporary time. Eg: 1m, 1h, 1d. Default: 1h
	// +kubebuilder:validation:Optional
	TemporaryRange *string `json:"temporaryRange,omitempty" tf:"temporary_range,omitempty"`
}

type UserInitParameters struct {
}

type UserObservation struct {

	// (String) The email of the user
	// The email of the user
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The first name of the user
	// The first name of the user
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// (String) The ID of the project user role.
	// The id of the user
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The last name of the user
	// The last name of the user
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`
}

type UserParameters struct {
}

// ProjectUserSpec defines the desired state of ProjectUser
type ProjectUserSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ProjectUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectUserInitParameters `json:"initProvider,omitempty"`
}

// ProjectUserStatus defines the observed state of ProjectUser.
type ProjectUserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ProjectUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectUser is the Schema for the ProjectUsers API. Create project users & save to Infisical. Only Machine Identity authentication is supported for this resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type ProjectUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   ProjectUserSpec   `json:"spec"`
	Status ProjectUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectUserList contains a list of ProjectUsers
type ProjectUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectUser `json:"items"`
}

// Repository type metadata.
var (
	ProjectUser_Kind             = "ProjectUser"
	ProjectUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectUser_Kind}.String()
	ProjectUser_KindAPIVersion   = ProjectUser_Kind + "." + CRDGroupVersion.String()
	ProjectUser_GroupVersionKind = CRDGroupVersion.WithKind(ProjectUser_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectUser{}, &ProjectUserList{})
}
