// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConditionsInitParameters struct {

	// (String) The environment slug this permission should allow.
	// The environment slug this permission should allow.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The secret path this permission should be scoped to
	// The secret path this permission should be scoped to
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`
}

type ConditionsObservation struct {

	// (String) The environment slug this permission should allow.
	// The environment slug this permission should allow.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The secret path this permission should be scoped to
	// The secret path this permission should be scoped to
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`
}

type ConditionsParameters struct {

	// (String) The environment slug this permission should allow.
	// The environment slug this permission should allow.
	// +kubebuilder:validation:Optional
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The secret path this permission should be scoped to
	// The secret path this permission should be scoped to
	// +kubebuilder:validation:Optional
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`
}

type PermissionsInitParameters struct {

	// (String) Describe what action an entity can take. Enum: create,edit,delete,read
	// Describe what action an entity can take. Enum: create,edit,delete,read
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (Attributes) The conditions to scope permissions (see below for nested schema)
	Conditions *ConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	// Describe what action an entity can take. Enum: role,member,groups,settings,integrations,webhooks,service-tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type PermissionsObservation struct {

	// (String) Describe what action an entity can take. Enum: create,edit,delete,read
	// Describe what action an entity can take. Enum: create,edit,delete,read
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (Attributes) The conditions to scope permissions (see below for nested schema)
	Conditions *ConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	// Describe what action an entity can take. Enum: role,member,groups,settings,integrations,webhooks,service-tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type PermissionsParameters struct {

	// (String) Describe what action an entity can take. Enum: create,edit,delete,read
	// Describe what action an entity can take. Enum: create,edit,delete,read
	// +kubebuilder:validation:Optional
	Action *string `json:"action" tf:"action,omitempty"`

	// (Attributes) The conditions to scope permissions (see below for nested schema)
	// +kubebuilder:validation:Optional
	Conditions *ConditionsParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	// Describe what action an entity can take. Enum: role,member,groups,settings,integrations,webhooks,service-tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type PermissionsV2InitParameters struct {

	// (String) Describe what action an entity can take. Enum: create,edit,delete,read
	// Describe what actions an entity can take.
	// +listType=set
	Action []*string `json:"action,omitempty" tf:"action,omitempty"`

	// (Attributes) The conditions to scope permissions (see below for nested schema)
	// When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	Conditions *string `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Boolean) Whether rule forbids. Set this to true if permission forbids.
	// Whether rule forbids. Set this to true if permission forbids.
	Inverted *bool `json:"inverted,omitempty" tf:"inverted,omitempty"`

	// tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	// Describe the entity the permission pertains to.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type PermissionsV2Observation struct {

	// (String) Describe what action an entity can take. Enum: create,edit,delete,read
	// Describe what actions an entity can take.
	// +listType=set
	Action []*string `json:"action,omitempty" tf:"action,omitempty"`

	// (Attributes) The conditions to scope permissions (see below for nested schema)
	// When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	Conditions *string `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Boolean) Whether rule forbids. Set this to true if permission forbids.
	// Whether rule forbids. Set this to true if permission forbids.
	Inverted *bool `json:"inverted,omitempty" tf:"inverted,omitempty"`

	// tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	// Describe the entity the permission pertains to.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type PermissionsV2Parameters struct {

	// (String) Describe what action an entity can take. Enum: create,edit,delete,read
	// Describe what actions an entity can take.
	// +kubebuilder:validation:Optional
	// +listType=set
	Action []*string `json:"action" tf:"action,omitempty"`

	// (Attributes) The conditions to scope permissions (see below for nested schema)
	// When specified, only matching conditions will be allowed to access given resource. Refer to the documentation in https://infisical.com/docs/internals/permissions#conditions for the complete list of supported properties and operators.
	// +kubebuilder:validation:Optional
	Conditions *string `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (Boolean) Whether rule forbids. Set this to true if permission forbids.
	// Whether rule forbids. Set this to true if permission forbids.
	// +kubebuilder:validation:Optional
	Inverted *bool `json:"inverted,omitempty" tf:"inverted,omitempty"`

	// tokens,environments,tags,audit-logs,ip-allowlist,workspace,secrets,secret-rollback,secret-approval,secret-rotation,secret-validation-rules,identity,certificate-authorities,certificates,certificate-policies,kms,pki-alerts,pki-collections
	// Describe the entity the permission pertains to.
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type ProjectRoleInitParameters struct {

	// (String) The description for the new role. Defaults to an empty string.
	// The description for the new role. Defaults to an empty string.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name for the new role
	// The name for the new role
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// from-permission-v1-to-permission-v2) The permissions assigned to the project role (see below for nested schema)
	Permissions []PermissionsInitParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// permissions for its usage. (see below for nested schema)
	PermissionsV2 []PermissionsV2InitParameters `json:"permissionsV2,omitempty" tf:"permissions_v2,omitempty"`

	// (String) The ID of the project to create role. Must provide either project_id or project_slug, but not both.
	// The ID of the project to create role. Must provide either project_id or project_slug, but not both.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The slug of the project to create role. Must provide either project_slug or project_id, but not both.
	// The slug of the project to create role. Must provide either project_slug or project_id, but not both.
	ProjectSlug *string `json:"projectSlug,omitempty" tf:"project_slug,omitempty"`

	// (String) The slug for the new role
	// The slug for the new role
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type ProjectRoleObservation struct {

	// (String) The description for the new role. Defaults to an empty string.
	// The description for the new role. Defaults to an empty string.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of the role
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name for the new role
	// The name for the new role
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// from-permission-v1-to-permission-v2) The permissions assigned to the project role (see below for nested schema)
	Permissions []PermissionsObservation `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// permissions for its usage. (see below for nested schema)
	PermissionsV2 []PermissionsV2Observation `json:"permissionsV2,omitempty" tf:"permissions_v2,omitempty"`

	// (String) The ID of the project to create role. Must provide either project_id or project_slug, but not both.
	// The ID of the project to create role. Must provide either project_id or project_slug, but not both.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The slug of the project to create role. Must provide either project_slug or project_id, but not both.
	// The slug of the project to create role. Must provide either project_slug or project_id, but not both.
	ProjectSlug *string `json:"projectSlug,omitempty" tf:"project_slug,omitempty"`

	// (String) The slug for the new role
	// The slug for the new role
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

type ProjectRoleParameters struct {

	// (String) The description for the new role. Defaults to an empty string.
	// The description for the new role. Defaults to an empty string.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The name for the new role
	// The name for the new role
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// from-permission-v1-to-permission-v2) The permissions assigned to the project role (see below for nested schema)
	// +kubebuilder:validation:Optional
	Permissions []PermissionsParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// permissions for its usage. (see below for nested schema)
	// +kubebuilder:validation:Optional
	PermissionsV2 []PermissionsV2Parameters `json:"permissionsV2,omitempty" tf:"permissions_v2,omitempty"`

	// (String) The ID of the project to create role. Must provide either project_id or project_slug, but not both.
	// The ID of the project to create role. Must provide either project_id or project_slug, but not both.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The slug of the project to create role. Must provide either project_slug or project_id, but not both.
	// The slug of the project to create role. Must provide either project_slug or project_id, but not both.
	// +kubebuilder:validation:Optional
	ProjectSlug *string `json:"projectSlug,omitempty" tf:"project_slug,omitempty"`

	// (String) The slug for the new role
	// The slug for the new role
	// +kubebuilder:validation:Optional
	Slug *string `json:"slug,omitempty" tf:"slug,omitempty"`
}

// ProjectRoleSpec defines the desired state of ProjectRole
type ProjectRoleSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ProjectRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectRoleInitParameters `json:"initProvider,omitempty"`
}

// ProjectRoleStatus defines the observed state of ProjectRole.
type ProjectRoleStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ProjectRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectRole is the Schema for the ProjectRoles API. Create custom project roles & save to Infisical. Only Machine Identity authentication is supported for this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type ProjectRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.slug) || (has(self.initProvider) && has(self.initProvider.slug))",message="spec.forProvider.slug is a required parameter"
	Spec   ProjectRoleSpec   `json:"spec"`
	Status ProjectRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectRoleList contains a list of ProjectRoles
type ProjectRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectRole `json:"items"`
}

// Repository type metadata.
var (
	ProjectRole_Kind             = "ProjectRole"
	ProjectRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectRole_Kind}.String()
	ProjectRole_KindAPIVersion   = ProjectRole_Kind + "." + CRDGroupVersion.String()
	ProjectRole_GroupVersionKind = CRDGroupVersion.WithKind(ProjectRole_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectRole{}, &ProjectRoleList{})
}
