// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SecretApprovalPolicyApproversInitParameters struct {

	// (String) The ID of the secret approval policy
	// The ID of the approver
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The type of approver. Either group or user
	// The type of approver. Either group or user
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The username of the approver. By default, this is the email
	// The username of the approver. By default, this is the email
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SecretApprovalPolicyApproversObservation struct {

	// (String) The ID of the secret approval policy
	// The ID of the approver
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The type of approver. Either group or user
	// The type of approver. Either group or user
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The username of the approver. By default, this is the email
	// The username of the approver. By default, this is the email
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SecretApprovalPolicyApproversParameters struct {

	// (String) The ID of the secret approval policy
	// The ID of the approver
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The type of approver. Either group or user
	// The type of approver. Either group or user
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// (String) The username of the approver. By default, this is the email
	// The username of the approver. By default, this is the email
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SecretApprovalPolicyBypassersInitParameters struct {

	// (String) The ID of the secret approval policy
	// The ID of the bypasser
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The type of approver. Either group or user
	// The type of bypasser. Either group or user
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The username of the approver. By default, this is the email
	// The username of the bypasser. By default, this is the email
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SecretApprovalPolicyBypassersObservation struct {

	// (String) The ID of the secret approval policy
	// The ID of the bypasser
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The type of approver. Either group or user
	// The type of bypasser. Either group or user
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The username of the approver. By default, this is the email
	// The username of the bypasser. By default, this is the email
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SecretApprovalPolicyBypassersParameters struct {

	// (String) The ID of the secret approval policy
	// The ID of the bypasser
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The type of approver. Either group or user
	// The type of bypasser. Either group or user
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// (String) The username of the approver. By default, this is the email
	// The username of the bypasser. By default, this is the email
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SecretApprovalPolicyInitParameters struct {

	// (Boolean) Whether to allow the  approvers to approve their own changes
	// Whether to allow the  approvers to approve their own changes
	AllowSelfApproval *bool `json:"allowSelfApproval,omitempty" tf:"allow_self_approval,omitempty"`

	// (Attributes Set) The required approvers (see below for nested schema)
	Approvers []SecretApprovalPolicyApproversInitParameters `json:"approvers,omitempty" tf:"approvers,omitempty"`

	// (Boolean) Whether machine identities can bypass the approval policy. If omitted when the policy is created, it defaults to false. Removing this attribute later does not reset it: for example, if it is set to true and you then delete it from your configuration, the policy keeps true. To disable it, set it to false explicitly.
	// Whether machine identities can bypass the approval policy. If omitted when the policy is created, it defaults to `false`. Removing this attribute later does not reset it: for example, if it is set to `true` and you then delete it from your configuration, the policy keeps `true`. To disable it, set it to `false` explicitly.
	BypassApprovalsForMachineIdentities *bool `json:"bypassApprovalsForMachineIdentities,omitempty" tf:"bypass_approvals_for_machine_identities,omitempty"`

	// (Attributes Set) The bypassers who can bypass the approval policy (see below for nested schema)
	Bypassers []SecretApprovalPolicyBypassersInitParameters `json:"bypassers,omitempty" tf:"bypassers,omitempty"`

	// (String) The enforcement level of the policy. This can either be hard or soft
	// The enforcement level of the policy. This can either be hard or soft
	EnforcementLevel *string `json:"enforcementLevel,omitempty" tf:"enforcement_level,omitempty"`

	// (String) (DEPRECATED, Use environment_slugs instead) The environment to apply the secret approval policy to
	// (DEPRECATED, Use environment_slugs instead) The environment to apply the secret approval policy to
	EnvironmentSlug *string `json:"environmentSlug,omitempty" tf:"environment_slug,omitempty"`

	// (List of String) The environments to apply the secret approval policy to
	// The environments to apply the secret approval policy to
	EnvironmentSlugs []*string `json:"environmentSlugs,omitempty" tf:"environment_slugs,omitempty"`

	// (String) The name of the secret approval policy
	// The name of the secret approval policy
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the project to add the secret approval policy
	// The ID of the project to add the secret approval policy
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha2.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Number) The number of required approvers
	// The number of required approvers
	RequiredApprovals *float64 `json:"requiredApprovals,omitempty" tf:"required_approvals,omitempty"`

	// (String) The secret path to apply the secret approval policy to
	// The secret path to apply the secret approval policy to
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`
}

type SecretApprovalPolicyObservation struct {

	// (Boolean) Whether to allow the  approvers to approve their own changes
	// Whether to allow the  approvers to approve their own changes
	AllowSelfApproval *bool `json:"allowSelfApproval,omitempty" tf:"allow_self_approval,omitempty"`

	// (Attributes Set) The required approvers (see below for nested schema)
	Approvers []SecretApprovalPolicyApproversObservation `json:"approvers,omitempty" tf:"approvers,omitempty"`

	// (Boolean) Whether machine identities can bypass the approval policy. If omitted when the policy is created, it defaults to false. Removing this attribute later does not reset it: for example, if it is set to true and you then delete it from your configuration, the policy keeps true. To disable it, set it to false explicitly.
	// Whether machine identities can bypass the approval policy. If omitted when the policy is created, it defaults to `false`. Removing this attribute later does not reset it: for example, if it is set to `true` and you then delete it from your configuration, the policy keeps `true`. To disable it, set it to `false` explicitly.
	BypassApprovalsForMachineIdentities *bool `json:"bypassApprovalsForMachineIdentities,omitempty" tf:"bypass_approvals_for_machine_identities,omitempty"`

	// (Attributes Set) The bypassers who can bypass the approval policy (see below for nested schema)
	Bypassers []SecretApprovalPolicyBypassersObservation `json:"bypassers,omitempty" tf:"bypassers,omitempty"`

	// (String) The enforcement level of the policy. This can either be hard or soft
	// The enforcement level of the policy. This can either be hard or soft
	EnforcementLevel *string `json:"enforcementLevel,omitempty" tf:"enforcement_level,omitempty"`

	// (String) (DEPRECATED, Use environment_slugs instead) The environment to apply the secret approval policy to
	// (DEPRECATED, Use environment_slugs instead) The environment to apply the secret approval policy to
	EnvironmentSlug *string `json:"environmentSlug,omitempty" tf:"environment_slug,omitempty"`

	// (List of String) The environments to apply the secret approval policy to
	// The environments to apply the secret approval policy to
	EnvironmentSlugs []*string `json:"environmentSlugs,omitempty" tf:"environment_slugs,omitempty"`

	// (String) The ID of the secret approval policy
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the secret approval policy
	// The name of the secret approval policy
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the project to add the secret approval policy
	// The ID of the project to add the secret approval policy
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) The number of required approvers
	// The number of required approvers
	RequiredApprovals *float64 `json:"requiredApprovals,omitempty" tf:"required_approvals,omitempty"`

	// (String) The secret path to apply the secret approval policy to
	// The secret path to apply the secret approval policy to
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`
}

type SecretApprovalPolicyParameters struct {

	// (Boolean) Whether to allow the  approvers to approve their own changes
	// Whether to allow the  approvers to approve their own changes
	// +kubebuilder:validation:Optional
	AllowSelfApproval *bool `json:"allowSelfApproval,omitempty" tf:"allow_self_approval,omitempty"`

	// (Attributes Set) The required approvers (see below for nested schema)
	// +kubebuilder:validation:Optional
	Approvers []SecretApprovalPolicyApproversParameters `json:"approvers,omitempty" tf:"approvers,omitempty"`

	// (Boolean) Whether machine identities can bypass the approval policy. If omitted when the policy is created, it defaults to false. Removing this attribute later does not reset it: for example, if it is set to true and you then delete it from your configuration, the policy keeps true. To disable it, set it to false explicitly.
	// Whether machine identities can bypass the approval policy. If omitted when the policy is created, it defaults to `false`. Removing this attribute later does not reset it: for example, if it is set to `true` and you then delete it from your configuration, the policy keeps `true`. To disable it, set it to `false` explicitly.
	// +kubebuilder:validation:Optional
	BypassApprovalsForMachineIdentities *bool `json:"bypassApprovalsForMachineIdentities,omitempty" tf:"bypass_approvals_for_machine_identities,omitempty"`

	// (Attributes Set) The bypassers who can bypass the approval policy (see below for nested schema)
	// +kubebuilder:validation:Optional
	Bypassers []SecretApprovalPolicyBypassersParameters `json:"bypassers,omitempty" tf:"bypassers,omitempty"`

	// (String) The enforcement level of the policy. This can either be hard or soft
	// The enforcement level of the policy. This can either be hard or soft
	// +kubebuilder:validation:Optional
	EnforcementLevel *string `json:"enforcementLevel,omitempty" tf:"enforcement_level,omitempty"`

	// (String) (DEPRECATED, Use environment_slugs instead) The environment to apply the secret approval policy to
	// (DEPRECATED, Use environment_slugs instead) The environment to apply the secret approval policy to
	// +kubebuilder:validation:Optional
	EnvironmentSlug *string `json:"environmentSlug,omitempty" tf:"environment_slug,omitempty"`

	// (List of String) The environments to apply the secret approval policy to
	// The environments to apply the secret approval policy to
	// +kubebuilder:validation:Optional
	EnvironmentSlugs []*string `json:"environmentSlugs,omitempty" tf:"environment_slugs,omitempty"`

	// (String) The name of the secret approval policy
	// The name of the secret approval policy
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the project to add the secret approval policy
	// The ID of the project to add the secret approval policy
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha2.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Number) The number of required approvers
	// The number of required approvers
	// +kubebuilder:validation:Optional
	RequiredApprovals *float64 `json:"requiredApprovals,omitempty" tf:"required_approvals,omitempty"`

	// (String) The secret path to apply the secret approval policy to
	// The secret path to apply the secret approval policy to
	// +kubebuilder:validation:Optional
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`
}

// SecretApprovalPolicySpec defines the desired state of SecretApprovalPolicy
type SecretApprovalPolicySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SecretApprovalPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecretApprovalPolicyInitParameters `json:"initProvider,omitempty"`
}

// SecretApprovalPolicyStatus defines the observed state of SecretApprovalPolicy.
type SecretApprovalPolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SecretApprovalPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecretApprovalPolicy is the Schema for the SecretApprovalPolicys API. Create secret approval policy for your projects
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type SecretApprovalPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.approvers) || (has(self.initProvider) && has(self.initProvider.approvers))",message="spec.forProvider.approvers is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.requiredApprovals) || (has(self.initProvider) && has(self.initProvider.requiredApprovals))",message="spec.forProvider.requiredApprovals is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretPath) || (has(self.initProvider) && has(self.initProvider.secretPath))",message="spec.forProvider.secretPath is a required parameter"
	Spec   SecretApprovalPolicySpec   `json:"spec"`
	Status SecretApprovalPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecretApprovalPolicyList contains a list of SecretApprovalPolicys
type SecretApprovalPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecretApprovalPolicy `json:"items"`
}

// Repository type metadata.
var (
	SecretApprovalPolicy_Kind             = "SecretApprovalPolicy"
	SecretApprovalPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecretApprovalPolicy_Kind}.String()
	SecretApprovalPolicy_KindAPIVersion   = SecretApprovalPolicy_Kind + "." + CRDGroupVersion.String()
	SecretApprovalPolicy_GroupVersionKind = CRDGroupVersion.WithKind(SecretApprovalPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&SecretApprovalPolicy{}, &SecretApprovalPolicyList{})
}
