// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AppConnectionAzureClientSecretsInitParameters struct {

	// (Attributes) The credentials for the Azure Client Secrets App Connection (see below for nested schema)
	Credentials *CredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (String) An optional description for the Azure Client Secrets App Connection.
	// An optional description for the Azure Client Secrets App Connection.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// secret
	// The method used to authenticate with Azure Client Secrets. Possible values are: client-secret
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// friendly
	// The name of the Azure Client Secrets App Connection to create. Must be slug-friendly
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
	// The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha2.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`
}

type AppConnectionAzureClientSecretsObservation struct {

	// (Attributes) The credentials for the Azure Client Secrets App Connection (see below for nested schema)
	Credentials *CredentialsObservation `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (String) The hash of the Azure Client Secrets App Connection credentials
	// The hash of the Azure Client Secrets App Connection credentials
	CredentialsHash *string `json:"credentialsHash,omitempty" tf:"credentials_hash,omitempty"`

	// (String) An optional description for the Azure Client Secrets App Connection.
	// An optional description for the Azure Client Secrets App Connection.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of the app connection
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// secret
	// The method used to authenticate with Azure Client Secrets. Possible values are: client-secret
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// friendly
	// The name of the Azure Client Secrets App Connection to create. Must be slug-friendly
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
	// The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type AppConnectionAzureClientSecretsParameters struct {

	// (Attributes) The credentials for the Azure Client Secrets App Connection (see below for nested schema)
	// +kubebuilder:validation:Optional
	Credentials *CredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (String) An optional description for the Azure Client Secrets App Connection.
	// An optional description for the Azure Client Secrets App Connection.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// secret
	// The method used to authenticate with Azure Client Secrets. Possible values are: client-secret
	// +kubebuilder:validation:Optional
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// friendly
	// The name of the Azure Client Secrets App Connection to create. Must be slug-friendly
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
	// The ID of the project to scope the app connection to. If not provided, the app connection will be scoped to the organization.
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/project/v1alpha2.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`
}

type CredentialsInitParameters struct {

	// secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// The Azure application (client) ID. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	ClientIDSecretRef v2.SecretKeySelector `json:"clientIdSecretRef" tf:"-"`

	// secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// The Azure client secret. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	ClientSecretSecretRef v2.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// The Azure Active Directory (AAD) tenant ID. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type CredentialsObservation struct {

	// secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// The Azure Active Directory (AAD) tenant ID. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type CredentialsParameters struct {

	// secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// The Azure application (client) ID. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// +kubebuilder:validation:Optional
	ClientIDSecretRef v2.SecretKeySelector `json:"clientIdSecretRef" tf:"-"`

	// secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// The Azure client secret. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef v2.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// The Azure Active Directory (AAD) tenant ID. Required for client-secret method. For more details, refer to the documentation here infisical.com/docs/integrations/app-connections/azure-client-secrets
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId" tf:"tenant_id,omitempty"`
}

// AppConnectionAzureClientSecretsSpec defines the desired state of AppConnectionAzureClientSecrets
type AppConnectionAzureClientSecretsSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AppConnectionAzureClientSecretsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AppConnectionAzureClientSecretsInitParameters `json:"initProvider,omitempty"`
}

// AppConnectionAzureClientSecretsStatus defines the observed state of AppConnectionAzureClientSecrets.
type AppConnectionAzureClientSecretsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AppConnectionAzureClientSecretsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AppConnectionAzureClientSecrets is the Schema for the AppConnectionAzureClientSecretss API. Create and manage Azure Client Secrets App Connection
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type AppConnectionAzureClientSecrets struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.credentials) || (has(self.initProvider) && has(self.initProvider.credentials))",message="spec.forProvider.credentials is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.method) || (has(self.initProvider) && has(self.initProvider.method))",message="spec.forProvider.method is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AppConnectionAzureClientSecretsSpec   `json:"spec"`
	Status AppConnectionAzureClientSecretsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AppConnectionAzureClientSecretsList contains a list of AppConnectionAzureClientSecretss
type AppConnectionAzureClientSecretsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AppConnectionAzureClientSecrets `json:"items"`
}

// Repository type metadata.
var (
	AppConnectionAzureClientSecrets_Kind             = "AppConnectionAzureClientSecrets"
	AppConnectionAzureClientSecrets_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AppConnectionAzureClientSecrets_Kind}.String()
	AppConnectionAzureClientSecrets_KindAPIVersion   = AppConnectionAzureClientSecrets_Kind + "." + CRDGroupVersion.String()
	AppConnectionAzureClientSecrets_GroupVersionKind = CRDGroupVersion.WithKind(AppConnectionAzureClientSecrets_Kind)
)

func init() {
	SchemeBuilder.Register(&AppConnectionAzureClientSecrets{}, &AppConnectionAzureClientSecretsList{})
}
