apiVersion: project.crossplane.infisical.com/v1alpha1
kind: ProjectGroup
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/projectgroup
  labels:
    testing.upbound.io/example-name: test-group
  name: test-group
spec:
  forProvider:
    groupId: <group-id>
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    roles: '[{"role_slug": "admin"}]'

---

apiVersion: project.crossplane.infisical.com/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/projectgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
    slug: example
