apiVersion: project.crossplane.infisical.com/v1alpha1
kind: SecretApprovalPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/secretapprovalpolicy
  labels:
    testing.upbound.io/example-name: prod-policy
  name: prod-policy
spec:
  forProvider:
    allowSelfApproval: false
    enforcementLevel: soft
    environmentSlugs:
    - prod
    groupApprovers:
    - 6629e33a-ab1d-4d0d-958b-63640e7988db
    groupBypassers:
    - 6629e33a-ab1d-4d0d-958b-63640e7988db
    name: my-secret-approval-policy
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    requiredApprovals: 2
    secretPath: /
    userApprovers:
    - admin@infisical.com
    userBypassers:
    - admin@infisical.com
