apiVersion: project.crossplane.infisical.com/v1alpha2
kind: SecretApprovalPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha2/secretapprovalpolicy
  labels:
    testing.upbound.io/example-name: prod-policy
  name: prod-policy
spec:
  forProvider:
    approvers:
    - id: 52c70c28-9504-4b88-b5af-ca2495dd277d
      type: group
    - type: user
      username: name@infisical.com
    bypassApprovalsForMachineIdentities: false
    enforcementLevel: hard
    environmentSlugs:
    - prod
    name: my-prod-policy
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    requiredApprovals: 1
    secretPath: /

---

apiVersion: project.crossplane.infisical.com/v1alpha2
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha2/secretapprovalpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
    slug: example
