apiVersion: secretsync.crossplane.infisical.com/v1alpha1
kind: SecretSyncAWSParameterStore
metadata:
  annotations:
    meta.upbound.io/example-id: secretsync/v1alpha1/secretsyncawsparameterstore
  labels:
    testing.upbound.io/example-name: aws-parameter-store-secret-sync
  name: aws-parameter-store-secret-sync
spec:
  forProvider:
    connectionId: <app-connection-id>
    description: Demo of AWS Parameter Store secret sync
    destinationConfig: '{"aws_region":"<aws-region>","path":"/example/secrets/"}'
    environment: <environment-slug>
    name: aws-parameter-store-secret-sync-demo
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretPath: <secret-path>
    syncOptions: '{"initial_sync_behavior":"overwrite-destination","aws_kms_key_id":"<aws-kms-key-id>","sync_secret_metadata_as_tags":false,"tags":[{"key":"tag-1","value":"tag-1-value"},{"key":"tag-2","value":"tag-2-value"}]}'
