apiVersion: secret.crossplane.infisical.com/v1alpha2
kind: SecretFolder
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha2/secretfolder
  labels:
    testing.upbound.io/example-name: folder-1
  name: folder-1
spec:
  forProvider:
    description: This is a description of the folder
    environmentSlug: dev
    folderPath: /
    name: folder-1
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
