//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersInitParameters) DeepCopyInto(out *ParametersInitParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ObjectID != nil {
		in, out := &in.ObjectID, &out.ObjectID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersInitParameters.
func (in *ParametersInitParameters) DeepCopy() *ParametersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ParametersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersObservation) DeepCopyInto(out *ParametersObservation) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ObjectID != nil {
		in, out := &in.ObjectID, &out.ObjectID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersObservation.
func (in *ParametersObservation) DeepCopy() *ParametersObservation {
	if in == nil {
		return nil
	}
	out := new(ParametersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersParameters) DeepCopyInto(out *ParametersParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ObjectID != nil {
		in, out := &in.ObjectID, &out.ObjectID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersParameters.
func (in *ParametersParameters) DeepCopy() *ParametersParameters {
	if in == nil {
		return nil
	}
	out := new(ParametersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotateAtUtcInitParameters) DeepCopyInto(out *RotateAtUtcInitParameters) {
	*out = *in
	if in.Hours != nil {
		in, out := &in.Hours, &out.Hours
		*out = new(float64)
		**out = **in
	}
	if in.Minutes != nil {
		in, out := &in.Minutes, &out.Minutes
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotateAtUtcInitParameters.
func (in *RotateAtUtcInitParameters) DeepCopy() *RotateAtUtcInitParameters {
	if in == nil {
		return nil
	}
	out := new(RotateAtUtcInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotateAtUtcObservation) DeepCopyInto(out *RotateAtUtcObservation) {
	*out = *in
	if in.Hours != nil {
		in, out := &in.Hours, &out.Hours
		*out = new(float64)
		**out = **in
	}
	if in.Minutes != nil {
		in, out := &in.Minutes, &out.Minutes
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotateAtUtcObservation.
func (in *RotateAtUtcObservation) DeepCopy() *RotateAtUtcObservation {
	if in == nil {
		return nil
	}
	out := new(RotateAtUtcObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotateAtUtcParameters) DeepCopyInto(out *RotateAtUtcParameters) {
	*out = *in
	if in.Hours != nil {
		in, out := &in.Hours, &out.Hours
		*out = new(float64)
		**out = **in
	}
	if in.Minutes != nil {
		in, out := &in.Minutes, &out.Minutes
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotateAtUtcParameters.
func (in *RotateAtUtcParameters) DeepCopy() *RotateAtUtcParameters {
	if in == nil {
		return nil
	}
	out := new(RotateAtUtcParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationAzureClientSecret) DeepCopyInto(out *SecretRotationAzureClientSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationAzureClientSecret.
func (in *SecretRotationAzureClientSecret) DeepCopy() *SecretRotationAzureClientSecret {
	if in == nil {
		return nil
	}
	out := new(SecretRotationAzureClientSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretRotationAzureClientSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationAzureClientSecretInitParameters) DeepCopyInto(out *SecretRotationAzureClientSecretInitParameters) {
	*out = *in
	if in.AutoRotationEnabled != nil {
		in, out := &in.AutoRotationEnabled, &out.AutoRotationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.ConnectionIDRef != nil {
		in, out := &in.ConnectionIDRef, &out.ConnectionIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionIDSelector != nil {
		in, out := &in.ConnectionIDSelector, &out.ConnectionIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(ParametersInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RotateAtUtc != nil {
		in, out := &in.RotateAtUtc, &out.RotateAtUtc
		*out = new(RotateAtUtcInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationInterval != nil {
		in, out := &in.RotationInterval, &out.RotationInterval
		*out = new(float64)
		**out = **in
	}
	if in.SecretPath != nil {
		in, out := &in.SecretPath, &out.SecretPath
		*out = new(string)
		**out = **in
	}
	if in.SecretsMapping != nil {
		in, out := &in.SecretsMapping, &out.SecretsMapping
		*out = new(SecretsMappingInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.TemporaryParameters != nil {
		in, out := &in.TemporaryParameters, &out.TemporaryParameters
		*out = new(TemporaryParametersInitParameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationAzureClientSecretInitParameters.
func (in *SecretRotationAzureClientSecretInitParameters) DeepCopy() *SecretRotationAzureClientSecretInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecretRotationAzureClientSecretInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationAzureClientSecretList) DeepCopyInto(out *SecretRotationAzureClientSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretRotationAzureClientSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationAzureClientSecretList.
func (in *SecretRotationAzureClientSecretList) DeepCopy() *SecretRotationAzureClientSecretList {
	if in == nil {
		return nil
	}
	out := new(SecretRotationAzureClientSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretRotationAzureClientSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationAzureClientSecretObservation) DeepCopyInto(out *SecretRotationAzureClientSecretObservation) {
	*out = *in
	if in.AutoRotationEnabled != nil {
		in, out := &in.AutoRotationEnabled, &out.AutoRotationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(ParametersObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RotateAtUtc != nil {
		in, out := &in.RotateAtUtc, &out.RotateAtUtc
		*out = new(RotateAtUtcObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationInterval != nil {
		in, out := &in.RotationInterval, &out.RotationInterval
		*out = new(float64)
		**out = **in
	}
	if in.SecretPath != nil {
		in, out := &in.SecretPath, &out.SecretPath
		*out = new(string)
		**out = **in
	}
	if in.SecretsMapping != nil {
		in, out := &in.SecretsMapping, &out.SecretsMapping
		*out = new(SecretsMappingObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.TemporaryParameters != nil {
		in, out := &in.TemporaryParameters, &out.TemporaryParameters
		*out = new(TemporaryParametersParameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationAzureClientSecretObservation.
func (in *SecretRotationAzureClientSecretObservation) DeepCopy() *SecretRotationAzureClientSecretObservation {
	if in == nil {
		return nil
	}
	out := new(SecretRotationAzureClientSecretObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationAzureClientSecretParameters) DeepCopyInto(out *SecretRotationAzureClientSecretParameters) {
	*out = *in
	if in.AutoRotationEnabled != nil {
		in, out := &in.AutoRotationEnabled, &out.AutoRotationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.ConnectionIDRef != nil {
		in, out := &in.ConnectionIDRef, &out.ConnectionIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionIDSelector != nil {
		in, out := &in.ConnectionIDSelector, &out.ConnectionIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(ParametersParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.RotateAtUtc != nil {
		in, out := &in.RotateAtUtc, &out.RotateAtUtc
		*out = new(RotateAtUtcParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.RotationInterval != nil {
		in, out := &in.RotationInterval, &out.RotationInterval
		*out = new(float64)
		**out = **in
	}
	if in.SecretPath != nil {
		in, out := &in.SecretPath, &out.SecretPath
		*out = new(string)
		**out = **in
	}
	if in.SecretsMapping != nil {
		in, out := &in.SecretsMapping, &out.SecretsMapping
		*out = new(SecretsMappingParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.TemporaryParameters != nil {
		in, out := &in.TemporaryParameters, &out.TemporaryParameters
		*out = new(TemporaryParametersParameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationAzureClientSecretParameters.
func (in *SecretRotationAzureClientSecretParameters) DeepCopy() *SecretRotationAzureClientSecretParameters {
	if in == nil {
		return nil
	}
	out := new(SecretRotationAzureClientSecretParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationAzureClientSecretSpec) DeepCopyInto(out *SecretRotationAzureClientSecretSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationAzureClientSecretSpec.
func (in *SecretRotationAzureClientSecretSpec) DeepCopy() *SecretRotationAzureClientSecretSpec {
	if in == nil {
		return nil
	}
	out := new(SecretRotationAzureClientSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationAzureClientSecretStatus) DeepCopyInto(out *SecretRotationAzureClientSecretStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationAzureClientSecretStatus.
func (in *SecretRotationAzureClientSecretStatus) DeepCopy() *SecretRotationAzureClientSecretStatus {
	if in == nil {
		return nil
	}
	out := new(SecretRotationAzureClientSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsMappingInitParameters) DeepCopyInto(out *SecretsMappingInitParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsMappingInitParameters.
func (in *SecretsMappingInitParameters) DeepCopy() *SecretsMappingInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecretsMappingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsMappingObservation) DeepCopyInto(out *SecretsMappingObservation) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsMappingObservation.
func (in *SecretsMappingObservation) DeepCopy() *SecretsMappingObservation {
	if in == nil {
		return nil
	}
	out := new(SecretsMappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsMappingParameters) DeepCopyInto(out *SecretsMappingParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsMappingParameters.
func (in *SecretsMappingParameters) DeepCopy() *SecretsMappingParameters {
	if in == nil {
		return nil
	}
	out := new(SecretsMappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporaryParametersInitParameters) DeepCopyInto(out *TemporaryParametersInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporaryParametersInitParameters.
func (in *TemporaryParametersInitParameters) DeepCopy() *TemporaryParametersInitParameters {
	if in == nil {
		return nil
	}
	out := new(TemporaryParametersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporaryParametersObservation) DeepCopyInto(out *TemporaryParametersObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporaryParametersObservation.
func (in *TemporaryParametersObservation) DeepCopy() *TemporaryParametersObservation {
	if in == nil {
		return nil
	}
	out := new(TemporaryParametersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporaryParametersParameters) DeepCopyInto(out *TemporaryParametersParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporaryParametersParameters.
func (in *TemporaryParametersParameters) DeepCopy() *TemporaryParametersParameters {
	if in == nil {
		return nil
	}
	out := new(TemporaryParametersParameters)
	in.DeepCopyInto(out)
	return out
}
