// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ParametersInitParameters struct {

	// (String) The client ID of the Azure Application to rotate the client secret for.
	// The client ID of the Azure Application to rotate the client secret for.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) The ID of the Azure Application to rotate the client secret for.
	// The ID of the Azure Application to rotate the client secret for.
	ObjectID *string `json:"objectId,omitempty" tf:"object_id,omitempty"`
}

type ParametersObservation struct {

	// (String) The client ID of the Azure Application to rotate the client secret for.
	// The client ID of the Azure Application to rotate the client secret for.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) The ID of the Azure Application to rotate the client secret for.
	// The ID of the Azure Application to rotate the client secret for.
	ObjectID *string `json:"objectId,omitempty" tf:"object_id,omitempty"`
}

type ParametersParameters struct {

	// (String) The client ID of the Azure Application to rotate the client secret for.
	// The client ID of the Azure Application to rotate the client secret for.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId" tf:"client_id,omitempty"`

	// (String) The ID of the Azure Application to rotate the client secret for.
	// The ID of the Azure Application to rotate the client secret for.
	// +kubebuilder:validation:Optional
	ObjectID *string `json:"objectId" tf:"object_id,omitempty"`
}

type RotateAtUtcInitParameters struct {

	// (Number) The hour at which the rotation should occur (UTC).
	// The hour at which the rotation should occur (UTC).
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (Number) The minute at which the rotation should occur (UTC).
	// The minute at which the rotation should occur (UTC).
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type RotateAtUtcObservation struct {

	// (Number) The hour at which the rotation should occur (UTC).
	// The hour at which the rotation should occur (UTC).
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (Number) The minute at which the rotation should occur (UTC).
	// The minute at which the rotation should occur (UTC).
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type RotateAtUtcParameters struct {

	// (Number) The hour at which the rotation should occur (UTC).
	// The hour at which the rotation should occur (UTC).
	// +kubebuilder:validation:Optional
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (Number) The minute at which the rotation should occur (UTC).
	// The minute at which the rotation should occur (UTC).
	// +kubebuilder:validation:Optional
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type SecretRotationAzureClientSecretInitParameters struct {

	// (Boolean) Whether secrets should be automatically rotated.
	// Whether secrets should be automatically rotated.
	AutoRotationEnabled *bool `json:"autoRotationEnabled,omitempty" tf:"auto_rotation_enabled,omitempty"`

	// (String) The ID of the connection to use for the secret rotation.
	// The ID of the connection to use for the secret rotation.
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/appconnection/v1alpha2.AppConnectionAzureClientSecrets
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// Reference to a AppConnectionAzureClientSecrets in appconnection to populate connectionId.
	// +kubebuilder:validation:Optional
	ConnectionIDRef *v2.Reference `json:"connectionIdRef,omitempty" tf:"-"`

	// Selector for a AppConnectionAzureClientSecrets in appconnection to populate connectionId.
	// +kubebuilder:validation:Optional
	ConnectionIDSelector *v2.Selector `json:"connectionIdSelector,omitempty" tf:"-"`

	// (String) The description of the secret rotation.
	// The description of the secret rotation.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The slug of the project environment to rotate secrets from.
	// The slug of the project environment to rotate secrets from.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The name of the secret rotation.
	// The name of the secret rotation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Parameters to modify how secrets are rotated. (see below for nested schema)
	Parameters *ParametersInitParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) The ID of the Infisical project to create the secret rotation in.
	// The ID of the Infisical project to create the secret rotation in.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) At which UTC time the rotation should occur. (see below for nested schema)
	RotateAtUtc *RotateAtUtcInitParameters `json:"rotateAtUtc,omitempty" tf:"rotate_at_utc,omitempty"`

	// (Number) How many days to wait between each rotation.
	// How many days to wait between each rotation.
	RotationInterval *float64 `json:"rotationInterval,omitempty" tf:"rotation_interval,omitempty"`

	// (String) The folder path to rotate secrets from.
	// The folder path to rotate secrets from.
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`

	// (Attributes) Secret mappings to modify how secrets are rotated. (see below for nested schema)
	SecretsMapping *SecretsMappingInitParameters `json:"secretsMapping,omitempty" tf:"secrets_mapping,omitempty"`

	// (Attributes) Temporary parameters to modify how secrets are rotated. (see below for nested schema)
	TemporaryParameters *TemporaryParametersInitParameters `json:"temporaryParameters,omitempty" tf:"temporary_parameters,omitempty"`
}

type SecretRotationAzureClientSecretObservation struct {

	// (Boolean) Whether secrets should be automatically rotated.
	// Whether secrets should be automatically rotated.
	AutoRotationEnabled *bool `json:"autoRotationEnabled,omitempty" tf:"auto_rotation_enabled,omitempty"`

	// (String) The ID of the connection to use for the secret rotation.
	// The ID of the connection to use for the secret rotation.
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// (String) The description of the secret rotation.
	// The description of the secret rotation.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The slug of the project environment to rotate secrets from.
	// The slug of the project environment to rotate secrets from.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The ID of the secret rotation.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the secret rotation.
	// The name of the secret rotation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Parameters to modify how secrets are rotated. (see below for nested schema)
	Parameters *ParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) The ID of the Infisical project to create the secret rotation in.
	// The ID of the Infisical project to create the secret rotation in.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) At which UTC time the rotation should occur. (see below for nested schema)
	RotateAtUtc *RotateAtUtcObservation `json:"rotateAtUtc,omitempty" tf:"rotate_at_utc,omitempty"`

	// (Number) How many days to wait between each rotation.
	// How many days to wait between each rotation.
	RotationInterval *float64 `json:"rotationInterval,omitempty" tf:"rotation_interval,omitempty"`

	// (String) The folder path to rotate secrets from.
	// The folder path to rotate secrets from.
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`

	// (Attributes) Secret mappings to modify how secrets are rotated. (see below for nested schema)
	SecretsMapping *SecretsMappingObservation `json:"secretsMapping,omitempty" tf:"secrets_mapping,omitempty"`

	// (Attributes) Temporary parameters to modify how secrets are rotated. (see below for nested schema)
	TemporaryParameters *TemporaryParametersParameters `json:"temporaryParameters,omitempty" tf:"temporary_parameters,omitempty"`
}

type SecretRotationAzureClientSecretParameters struct {

	// (Boolean) Whether secrets should be automatically rotated.
	// Whether secrets should be automatically rotated.
	// +kubebuilder:validation:Optional
	AutoRotationEnabled *bool `json:"autoRotationEnabled,omitempty" tf:"auto_rotation_enabled,omitempty"`

	// (String) The ID of the connection to use for the secret rotation.
	// The ID of the connection to use for the secret rotation.
	// +crossplane:generate:reference:type=github.com/infisical/provider-infisical/apis/appconnection/v1alpha2.AppConnectionAzureClientSecrets
	// +kubebuilder:validation:Optional
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// Reference to a AppConnectionAzureClientSecrets in appconnection to populate connectionId.
	// +kubebuilder:validation:Optional
	ConnectionIDRef *v2.Reference `json:"connectionIdRef,omitempty" tf:"-"`

	// Selector for a AppConnectionAzureClientSecrets in appconnection to populate connectionId.
	// +kubebuilder:validation:Optional
	ConnectionIDSelector *v2.Selector `json:"connectionIdSelector,omitempty" tf:"-"`

	// (String) The description of the secret rotation.
	// The description of the secret rotation.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The slug of the project environment to rotate secrets from.
	// The slug of the project environment to rotate secrets from.
	// +kubebuilder:validation:Optional
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The name of the secret rotation.
	// The name of the secret rotation.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Parameters to modify how secrets are rotated. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Parameters *ParametersParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) The ID of the Infisical project to create the secret rotation in.
	// The ID of the Infisical project to create the secret rotation in.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) At which UTC time the rotation should occur. (see below for nested schema)
	// +kubebuilder:validation:Optional
	RotateAtUtc *RotateAtUtcParameters `json:"rotateAtUtc,omitempty" tf:"rotate_at_utc,omitempty"`

	// (Number) How many days to wait between each rotation.
	// How many days to wait between each rotation.
	// +kubebuilder:validation:Optional
	RotationInterval *float64 `json:"rotationInterval,omitempty" tf:"rotation_interval,omitempty"`

	// (String) The folder path to rotate secrets from.
	// The folder path to rotate secrets from.
	// +kubebuilder:validation:Optional
	SecretPath *string `json:"secretPath,omitempty" tf:"secret_path,omitempty"`

	// (Attributes) Secret mappings to modify how secrets are rotated. (see below for nested schema)
	// +kubebuilder:validation:Optional
	SecretsMapping *SecretsMappingParameters `json:"secretsMapping,omitempty" tf:"secrets_mapping,omitempty"`

	// (Attributes) Temporary parameters to modify how secrets are rotated. (see below for nested schema)
	// +kubebuilder:validation:Optional
	TemporaryParameters *TemporaryParametersParameters `json:"temporaryParameters,omitempty" tf:"temporary_parameters,omitempty"`
}

type SecretsMappingInitParameters struct {

	// (String) The client ID of the Azure Application to rotate the client secret for.
	// The name of the secret that the client ID will be mapped to.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) The name of the secret that the rotated client secret will be mapped to.
	// The name of the secret that the rotated client secret will be mapped to.
	ClientSecret *string `json:"clientSecret,omitempty" tf:"client_secret,omitempty"`
}

type SecretsMappingObservation struct {

	// (String) The client ID of the Azure Application to rotate the client secret for.
	// The name of the secret that the client ID will be mapped to.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) The name of the secret that the rotated client secret will be mapped to.
	// The name of the secret that the rotated client secret will be mapped to.
	ClientSecret *string `json:"clientSecret,omitempty" tf:"client_secret,omitempty"`
}

type SecretsMappingParameters struct {

	// (String) The client ID of the Azure Application to rotate the client secret for.
	// The name of the secret that the client ID will be mapped to.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId" tf:"client_id,omitempty"`

	// (String) The name of the secret that the rotated client secret will be mapped to.
	// The name of the secret that the rotated client secret will be mapped to.
	// +kubebuilder:validation:Optional
	ClientSecret *string `json:"clientSecret" tf:"client_secret,omitempty"`
}

type TemporaryParametersInitParameters struct {
}

type TemporaryParametersObservation struct {
}

type TemporaryParametersParameters struct {
}

// SecretRotationAzureClientSecretSpec defines the desired state of SecretRotationAzureClientSecret
type SecretRotationAzureClientSecretSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SecretRotationAzureClientSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecretRotationAzureClientSecretInitParameters `json:"initProvider,omitempty"`
}

// SecretRotationAzureClientSecretStatus defines the observed state of SecretRotationAzureClientSecret.
type SecretRotationAzureClientSecretStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SecretRotationAzureClientSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecretRotationAzureClientSecret is the Schema for the SecretRotationAzureClientSecrets API. Create and manage Azure Client Secret Secret Rotations
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infisical}
type SecretRotationAzureClientSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parameters) || (has(self.initProvider) && has(self.initProvider.parameters))",message="spec.forProvider.parameters is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretPath) || (has(self.initProvider) && has(self.initProvider.secretPath))",message="spec.forProvider.secretPath is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretsMapping) || (has(self.initProvider) && has(self.initProvider.secretsMapping))",message="spec.forProvider.secretsMapping is a required parameter"
	Spec   SecretRotationAzureClientSecretSpec   `json:"spec"`
	Status SecretRotationAzureClientSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecretRotationAzureClientSecretList contains a list of SecretRotationAzureClientSecrets
type SecretRotationAzureClientSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecretRotationAzureClientSecret `json:"items"`
}

// Repository type metadata.
var (
	SecretRotationAzureClientSecret_Kind             = "SecretRotationAzureClientSecret"
	SecretRotationAzureClientSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecretRotationAzureClientSecret_Kind}.String()
	SecretRotationAzureClientSecret_KindAPIVersion   = SecretRotationAzureClientSecret_Kind + "." + CRDGroupVersion.String()
	SecretRotationAzureClientSecret_GroupVersionKind = CRDGroupVersion.WithKind(SecretRotationAzureClientSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&SecretRotationAzureClientSecret{}, &SecretRotationAzureClientSecretList{})
}
