apiVersion: secret.crossplane.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  annotations:
    meta.upbound.io/example-id: secret/v1alpha1/infisicalsecret
  labels:
    testing.upbound.io/example-name: mongo_secret
  name: mongo-secret
spec:
  forProvider:
    envSlug: dev
    folderPath: /
    name: MONGO_DB
    valueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    workspaceId: PROJECT_ID
