apiVersion: appconnection.crossplane.infisical.com/v1alpha2
kind: AppConnectionAzureClientSecrets
metadata:
  annotations:
    meta.upbound.io/example-id: appconnection/v1alpha2/appconnectionazureclientsecrets
  labels:
    testing.upbound.io/example-name: app_connection_azure_client_secret
  name: app-connection-azure-client-secret
spec:
  forProvider:
    credentials:
      clientIdSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      clientSecretSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      tenantId: <azure-tenant-id>
    description: I am a test Azure app connection using client credentials
    method: client-secret
    name: app_connection_azure_client_secret
